/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Controller.AutenticaLogin.nome;
import Controller.Cadastrar;
import Controller.CarregaTabelas;
import Model.Model_Estoque;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phelype
 */
public class EditaEstoque extends javax.swing.JFrame {
    private int valor1, valor2, result;

    /**
     * Creates new form EditaEstoque
     */
    
    private SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    public EditaEstoque() {
        initComponents();
        getContentPane().setBackground(Color.decode("#E8E8E8"));
        ListarTabelas();
        
    }
    public void ListarTabelas() {
        DefaultTableModel table = (DefaultTableModel) tblEdita.getModel();
        CarregaTabelas tbl = new CarregaTabelas();
        table.setNumRows(0);
        for (Model_Estoque est : tbl.CarregaTabelaN()) {
            table.addRow(new Object[]{
                est.getId_estoque(),
                est.getDescricao(),
                est.getQuant(),
                est.getData_cadastro(),
                est.getUser_cad(),
                est.getStatus(),});
        }
    }
     public String convertData(String data) {
        String dia = txtData.getText().substring(0, 2);
        String mes = txtData.getText().substring(3, 5);
        String ano = txtData.getText().substring(6);
        String dataf = ano + "-" + mes + "-" + dia;
        return dataf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdita = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCadPor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Estoque");

        tblEdita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Quant", "Data inserção", "Cad por", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEdita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditaMouseClicked(evt);
            }
        });
        tblEdita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblEditaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEdita);
        if (tblEdita.getColumnModel().getColumnCount() > 0) {
            tblEdita.getColumnModel().getColumn(0).setMinWidth(30);
            tblEdita.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setText("ID.:");

        txtID.setEditable(false);
        txtID.setBackground(java.awt.Color.orange);

        jLabel3.setText("Quant.:");

        jLabel4.setText("Data.:");

        txtData.setEditable(false);

        jLabel5.setText("Cad por.:");

        txtCadPor.setEditable(false);

        jLabel6.setText("Status.:");

        txtStatus.setEditable(false);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel7.setText("Descrição.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao)
                    .addComponent(txtCadPor)
                    .addComponent(txtStatus)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblEditaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditaMouseClicked
        if (tblEdita.getSelectedRow() != -1) {
            txtID.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 0).toString());
            txtDescricao.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 1).toString());
            txtData.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(),3).toString());
            txtCadPor.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 4).toString());
            txtStatus.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 5).toString());
            
            
        }
    }//GEN-LAST:event_tblEditaMouseClicked

    private void tblEditaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEditaKeyPressed
          if (tblEdita.getSelectedRow() != -1) {
            txtID.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 0).toString());
            txtDescricao.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 1).toString());
            txtData.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 3).toString());
            txtCadPor.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 4).toString());
            txtStatus.setText(tblEdita.getValueAt(tblEdita.getSelectedRow(), 5).toString());
            
            
        }
    }//GEN-LAST:event_tblEditaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valor1 = Integer.valueOf(tblEdita.getValueAt(tblEdita.getSelectedRow(), 2).toString());
        valor2 = Integer.valueOf(txtQuant.getText());
        
        result = valor1 + valor2;
        
        if (tblEdita.getSelectedRow() != -1) {
        Model_Estoque est = new Model_Estoque();
        Cadastrar cad = new Cadastrar();
        
        est.setDescricao(txtDescricao.getText());
        est.setQuant((result));
        est.setData_cadastro(String.valueOf(Date.valueOf(LocalDate.now())));
        HomePage home = new HomePage();
        est.setUser_cad(home.pega(nome));
        est.setId_estoque((int) tblEdita.getValueAt(tblEdita.getSelectedRow(), 0));
        cad.UpdateDB(est);
        
        ListarTabelas();
        if(est.getQuant() < 0){
            JOptionPane.showMessageDialog(null, "Atenção o Produto: "+est.getDescricao()+"está abaixo");
        }
        
        txtID.setText("");
        txtDescricao.setText("");
        txtQuant.setText("");
        txtData.setText("");
        txtCadPor.setText("");
        txtStatus.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEdita;
    private javax.swing.JTextField txtCadPor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
