/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Controller.AutenticaLogin.nome;
import Controller.CarregaCombox;
import Controller.CarregaTabelas;
import Controller.Controller_RegEnvios;
import static Controller.Controller_RegEnvios.id;
import Model.ItensReg;
import Model.ModelTransportadora;
import Model.RegEnvios;
import Model.RegItens;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phelype
 */
public class EnviosEquipamento extends javax.swing.JFrame {

    /**
     * Creates new form EnviosEquipamento
     */
    public EnviosEquipamento() {
        initComponents();
        getContentPane().setBackground(Color.getColor(nome, Color.decode("#E8E8E8")));
        jScrollPane1.getViewport().setBackground(Color.decode("#E8E8E8"));

        //Botões//
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnNovoRegistro.setEnabled(true);
        btnProcessar.setEnabled(false);
        /////////////////////////////////
        /////Text Dados envios///////////
        textCidadeDestino.setEnabled(false);
        textDestinatario.setEnabled(false);
        cbmTipoEnvio.setEnabled(false);
        checkSim.setEnabled(false);
        checkNao.setEnabled(false);
        ////////////////////////////////////////
        //////Panel Itens Enviados/////////
        cbmTipoItem.setEnabled(false);
        textDescricao.setEnabled(false);
        btnIncluir.setEnabled(false);
        CarregaCombox box = new CarregaCombox();
        for (ModelTransportadora trans : box.ListarTransportadora()) {
            cbmTipoEnvio.addItem(trans);
        }
        for (ItensReg itens : box.ListarItens()) {
            cbmTipoItem.addItem(itens);
        }
    }

    public int pegaId(int nId) {
        textId.setText(String.valueOf(nId));
        return nId;
    }

    public void ListarTabelas() {
        DefaultTableModel table = (DefaultTableModel) tableEnviados.getModel();
        CarregaTabelas tbl = new CarregaTabelas();
        table.setNumRows(0);
        for (RegItens model : tbl.CarregaHtsEstoque()) {
            table.addRow(new Object[]{
                model.getItem(),
                model.getDescricao(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textCidadeDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textDestinatario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbmTipoEnvio = new javax.swing.JComboBox<Object>();
        jPanel1 = new javax.swing.JPanel();
        checkSim = new javax.swing.JRadioButton();
        checkNao = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnProcessar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnNovoRegistro = new javax.swing.JButton();
        PanelItensEnviados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbmTipoItem = new javax.swing.JComboBox<Object>();
        jLabel5 = new javax.swing.JLabel();
        textDescricao = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnviados = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Envios Interior");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(232, 232, 232));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Cidade Destino.:");

        textCidadeDestino.setEnabled(false);

        jLabel2.setText("Destinatario.:");

        jLabel3.setText("Tipo Envio.:");

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Devolvido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        checkSim.setText("SIM");
        checkSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSimActionPerformed(evt);
            }
        });

        checkNao.setText("NÂO");
        checkNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkNao))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSim)
                    .addComponent(checkNao))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(textCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbmTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbmTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        btnCancelar.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar-red 50.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar.");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(53, 78));
        btnCancelar.setMinimumSize(new java.awt.Dimension(53, 78));
        btnCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnProcessar.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        btnProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Correto-50.png"))); // NOI18N
        btnProcessar.setText("Processar");
        btnProcessar.setToolTipText("Processar");
        btnProcessar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcessar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProcessar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save_envios-50.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setToolTipText("Gravar");
        btnGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGravar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnNovoRegistro.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        btnNovoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/registro-sava-50.png"))); // NOI18N
        btnNovoRegistro.setText("N Registro");
        btnNovoRegistro.setToolTipText("Novo Registro.");
        btnNovoRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovoRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNovoRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoRegistroActionPerformed(evt);
            }
        });

        PanelItensEnviados.setBackground(new java.awt.Color(232, 232, 232));
        PanelItensEnviados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Enviados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel4.setText("Tipo Item:");

        jLabel5.setText("Descrição item:");

        btnIncluir.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar_cor-30.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setToolTipText("Incluir");
        btnIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel7.setText("ID.:");

        textId.setEditable(false);
        textId.setBackground(new java.awt.Color(253, 194, 194));

        javax.swing.GroupLayout PanelItensEnviadosLayout = new javax.swing.GroupLayout(PanelItensEnviados);
        PanelItensEnviados.setLayout(PanelItensEnviadosLayout);
        PanelItensEnviadosLayout.setHorizontalGroup(
            PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelItensEnviadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbmTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelItensEnviadosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelItensEnviadosLayout.setVerticalGroup(
            PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelItensEnviadosLayout.createSequentialGroup()
                .addGroup(PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelItensEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelItensEnviadosLayout.createSequentialGroup()
                .addComponent(btnIncluir)
                .addContainerGap())
        );

        tableEnviados.setAutoCreateRowSorter(true);
        tableEnviados.setBorder(null);
        tableEnviados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo do Item", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tableEnviados);
        if (tableEnviados.getColumnModel().getColumnCount() > 0) {
            tableEnviados.getColumnModel().getColumn(0).setMinWidth(100);
            tableEnviados.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableEnviados.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel6.setText("Itens Enviados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelItensEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoRegistro)
                            .addComponent(btnGravar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcessar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelItensEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(935, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnNovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoRegistroActionPerformed
        btnProcessar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnNovoRegistro.setEnabled(false);
        btnCancelar.setEnabled(true);
        ////////Libera text Dados Enviados////////
        textCidadeDestino.setEnabled(true);
        textDestinatario.setEnabled(true);
        cbmTipoEnvio.setEnabled(true);
        checkSim.setEnabled(true);
        checkNao.setEnabled(true);
        ////////////////////////////////////////

    }//GEN-LAST:event_btnNovoRegistroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnNovoRegistro.setEnabled(true);
        btnGravar.setEnabled(false);
        btnProcessar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tableEnviados.removeAll();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        /*RegItens itens = new RegItens();
        Controller_RegEnvios reg = new Controller_RegEnvios();
        //Object valor = textId.getText();
        //itens.setEnvio_id((RegEnvios) valor);
        itens.setDescricao(textDescricao.getText());
        itens.setItem((ItensReg) cbmTipoItem.getSelectedItem());
        reg.CadRegItens(itens);

        textCidadeDestino.setText("");
        textDestinatario.setText("");
        cbmTipoEnvio.setSelectedItem(null);
        checkNao.setSelected(false);
        checkSim.setSelected(false);
        textId.setText("");
        cbmTipoItem.setSelectedItem(null);
        textDescricao.setText("");
        tableEnviados.removeEditor();
        
        ListarTabelas();*/


    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        /////Text Dados envios///////////
        /*textCidadeDestino.setEnabled(false);
         textDestinatario.setEnabled(false);
         cbmTipoEnvio.setEnabled(false);
         checkSim.setEnabled(false);
         checkNao.setEnabled(false);
         //////Panel Itens Enviados/////////
         cbmTipoItem.setEnabled(true);
         textDescricao.setEnabled(true);
         btnIncluir.setEnabled(true);
         ///////////////////////////////////*/
        RegEnvios envio = new RegEnvios();
        Controller_RegEnvios cont = new Controller_RegEnvios();
        if (textCidadeDestino.getText().equalsIgnoreCase("") || textDestinatario.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ooou, você realmente quer processar sem degitar nada ? Olha isso ai e tenta novamente !");
            textCidadeDestino.setEnabled(true);
            textDestinatario.setEnabled(true);
            cbmTipoEnvio.setEnabled(true);
            checkSim.setEnabled(true);
            checkNao.setEnabled(true);
            //////Panel Itens Enviados/////////
            cbmTipoItem.setEnabled(false);
            textDescricao.setEnabled(false);
            btnIncluir.setEnabled(true);
            btnGravar.setEnabled(false);
            btnProcessar.setEnabled(true);
        } else {
            envio.setCidade(textCidadeDestino.getText());
            envio.setTransp((ModelTransportadora) cbmTipoEnvio.getSelectedItem());
            envio.setData_envio(String.valueOf(LocalDate.now()));
            HomePage home = new HomePage();
            envio.setEnviadopor(home.pega(nome));
            envio.setDestinatario(textDestinatario.getText());
            if (checkSim.isSelected()) {
                envio.setDevolvido(true);
            } else {
                envio.setDevolvido(false);
            }
            cont.CadRegEnvios(envio);
            int soma = pegaId(id) + 2;
            textId.setText(String.valueOf(soma));
            btnProcessar.setEnabled(false);
            btnGravar.setEnabled(true);
            textCidadeDestino.setEnabled(false);
            textDestinatario.setEnabled(false);
            cbmTipoEnvio.setEnabled(false);
            checkSim.setEnabled(false);
            checkNao.setEnabled(false);
            PanelItensEnviados.setEnabled(true);
            cbmTipoItem.setEnabled(true);
            textDescricao.setEnabled(true);
            btnIncluir.setEnabled(true);
        }

    }//GEN-LAST:event_btnProcessarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        /*DefaultTableModel itensEnviados = (DefaultTableModel) tableEnviados.getModel();
         Object[] dados = {cbmTipoItem.getSelectedItem(), textDescricao.getText()};
         itensEnviados.addRow(dados);*/
        RegItens itens = new RegItens();
         Controller_RegEnvios reg = new Controller_RegEnvios();
         //Object valor = textId.getText();
         //itens.setEnvio_id((RegEnvios) valor);
         itens.setDescricao(textDescricao.getText());
         itens.setItem((ItensReg) cbmTipoItem.getSelectedItem());
         reg.CadRegItens(itens);
        
         textCidadeDestino.setText("");
         textDestinatario.setText("");
         cbmTipoEnvio.setSelectedItem(null);
         checkNao.setSelected(false);
         checkSim.setSelected(false);
         textId.setText("");
         cbmTipoItem.setSelectedItem(null);
         textDescricao.setText("");
         ListarTabelas();
         
        
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void checkSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSimActionPerformed
        checkNao.setSelected(false);
    }//GEN-LAST:event_checkSimActionPerformed

    private void checkNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNaoActionPerformed
        checkSim.setSelected(false);
    }//GEN-LAST:event_checkNaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviosEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviosEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviosEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviosEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviosEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelItensEnviados;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovoRegistro;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JComboBox<Object> cbmTipoEnvio;
    private javax.swing.JComboBox<Object> cbmTipoItem;
    private javax.swing.JRadioButton checkNao;
    private javax.swing.JRadioButton checkSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEnviados;
    private javax.swing.JTextField textCidadeDestino;
    private javax.swing.JTextField textDescricao;
    private javax.swing.JTextField textDestinatario;
    private javax.swing.JTextField textId;
    // End of variables declaration//GEN-END:variables
}
