/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.CarregaTabelas;
import DB_Conexao.ConexaoMySql;
import Model.Model_Estoque;
import Model.RetEstoqueM;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author phelype
 */
public class NewRetirada extends javax.swing.JFrame {
    private int valor, valorR, result;
    /**
     * Creates new form NewRetirada
     */
    public NewRetirada() {
        initComponents();
        getContentPane().setBackground(Color.decode("#E8E8E8"));
        jScrollPane1.getViewport().setBackground(Color.decode("#E8E8E8"));
        JTableHeader header = tblEstoque.getTableHeader();
        header.setBackground(Color.BLUE);
        //jTable1.setBackground(Color.red);
        ListarTabelas();

    }

    public void ListarTabelas() {
        DefaultTableModel table = (DefaultTableModel) tblEstoque.getModel();
        CarregaTabelas tbl = new CarregaTabelas();
        table.setNumRows(0);
        for (Model_Estoque model : tbl.CarregaTabelaN()) {

            table.addRow(new Object[]{
                model.getId_estoque(),
                model.getDescricao(),
                model.getQuant(),
                model.getData_cadastro(),
                model.getUser_cad(),
                model.getStatus(),
                model.getData_cadastro()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtQuant = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtCadPor = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtQuantR = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retirada Estoque");
        setResizable(false);

        tblEstoque.setBorder(null);
        tblEstoque.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 12)); // NOI18N
        tblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código.:", "Descrição.:", "Quant.:", "Entrada.:", "Cad. Por.:", "Situação.:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstoque);
        if (tblEstoque.getColumnModel().getColumnCount() > 0) {
            tblEstoque.getColumnModel().getColumn(0).setMinWidth(12);
            tblEstoque.getColumnModel().getColumn(0).setPreferredWidth(12);
            tblEstoque.getColumnModel().getColumn(1).setMinWidth(90);
            tblEstoque.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblEstoque.getColumnModel().getColumn(2).setMinWidth(30);
            tblEstoque.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblEstoque.getColumnModel().getColumn(3).setMinWidth(55);
            tblEstoque.getColumnModel().getColumn(3).setPreferredWidth(55);
            tblEstoque.getColumnModel().getColumn(5).setMinWidth(40);
            tblEstoque.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Retirada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(null);

        jLabel1.setText("ID.:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(17, 40, 23, 18);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(232, 232, 232));
        txtId.setForeground(java.awt.Color.black);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(110, 30, 46, 18);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(110, 50, 46, 13);

        jLabel4.setText("Descrição.:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 70, 75, 18);

        jLabel5.setText("Qant.:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 43, 18);

        jLabel6.setText("Entrada.:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 130, 63, 18);

        jLabel7.setText("Cad. Por.:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 160, 70, 18);

        jLabel8.setText("Status.:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 190, 52, 18);

        txtDescricao.setEditable(false);
        txtDescricao.setBackground(new java.awt.Color(232, 232, 232));
        txtDescricao.setForeground(java.awt.Color.black);
        txtDescricao.setBorder(null);
        jPanel1.add(txtDescricao);
        txtDescricao.setBounds(110, 60, 149, 18);

        txtQuant.setEditable(false);
        txtQuant.setBackground(new java.awt.Color(232, 232, 232));
        txtQuant.setForeground(java.awt.Color.black);
        txtQuant.setBorder(null);
        jPanel1.add(txtQuant);
        txtQuant.setBounds(110, 90, 150, 18);

        txtData.setEditable(false);
        txtData.setBackground(new java.awt.Color(232, 232, 232));
        txtData.setForeground(java.awt.Color.black);
        txtData.setBorder(null);
        jPanel1.add(txtData);
        txtData.setBounds(110, 120, 149, 18);

        txtCadPor.setEditable(false);
        txtCadPor.setBackground(new java.awt.Color(232, 232, 232));
        txtCadPor.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 10)); // NOI18N
        txtCadPor.setForeground(java.awt.Color.black);
        txtCadPor.setBorder(null);
        jPanel1.add(txtCadPor);
        txtCadPor.setBounds(110, 160, 149, 13);

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(232, 232, 232));
        txtStatus.setForeground(java.awt.Color.black);
        txtStatus.setBorder(null);
        jPanel1.add(txtStatus);
        txtStatus.setBounds(110, 180, 149, 18);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(110, 80, 149, 10);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(110, 110, 149, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(110, 140, 150, 3);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(110, 170, 150, 10);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(110, 200, 150, 10);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 370, 120, 32);

        jButton2.setText("Cancelar");
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 370, 110, 32);

        jLabel9.setText("Informe a quantidade a ser retirado.:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 220, 270, 18);

        txtQuantR.setBackground(new java.awt.Color(232, 232, 232));
        txtQuantR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantR.setBorder(null);
        txtQuantR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantRActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuantR);
        txtQuantR.setBounds(100, 240, 60, 18);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(100, 260, 60, 10);

        jScrollPane2.setViewportView(txtObservacao);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 250, 50);

        jLabel10.setText("Obervações.:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 290, 100, 18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tblEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstoqueMouseClicked
        if (tblEstoque.getSelectedRow() != -1) {
            txtId.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 0).toString());
            txtDescricao.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 1).toString());
            txtQuant.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 2).toString());
            txtData.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 3).toString());
            txtCadPor.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 4).toString());
            txtStatus.setText(tblEstoque.getValueAt(tblEstoque.getSelectedRow(), 5).toString());
        }

    }//GEN-LAST:event_tblEstoqueMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        RetEstoqueM m = new RetEstoqueM();
        m.setData_alteracao(Date.valueOf(LocalDate.now()));

        Connection con = ConexaoMySql.getConnection();
        PreparedStatement pst;
        String sql;
        try {
            sql = "insert into HtsEstoque(estoque_id, item_retirado, data_alteracao, editado, quant_retirado,obs) "
                    + "values('" + txtId.getText() + "','"+txtDescricao.getText()+"','" + m.getData_alteracao() + "','" + txtCadPor.getText() + "','" + txtQuantR.getText() + "','"+txtObservacao.getText()+"')";
            pst = con.prepareStatement(sql);
            pst.execute();
            valor = Integer.valueOf(txtQuant.getText());
            valorR = Integer.valueOf(txtQuantR.getText());
            result = valor - valorR;
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "OK !" + e.getMessage());
            ConexaoMySql.CloseConection(con);
        }catch(Error d){
            txtId.getText().equals("");
            JOptionPane.showMessageDialog(null, d.getMessage());
            ConexaoMySql.CloseConection(con);
        }
        String sql2;
        
        try {
            sql2 = "update Estoque set quant ='"+result+"' where id_estoque = '"+txtId.getText()+"'";
            pst = con.prepareStatement(sql2);
            pst.execute();
            ListarTabelas();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Atenção, erro ao Atualizar");
            ConexaoMySql.CloseConection(con);
        }catch(Error d){
            boolean equals = txtId.getText().equals("");
            JOptionPane.showMessageDialog(null, d.getMessage());
            ConexaoMySql.CloseConection(con);
        }
        
        txtId.setText("");
        txtDescricao.setText("");
        txtQuant.setText("");
        txtData.setText("");
        txtCadPor.setText("");
        txtStatus.setText("");
        txtQuantR.setText("");
        txtObservacao.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    private void txtQuantRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantRActionPerformed
    }//GEN-LAST:event_txtQuantRActionPerformed
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRetirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRetirada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tblEstoque;
    private javax.swing.JTextField txtCadPor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextPane txtObservacao;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuantR;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
